# Includes one of the default files in src/bootstrap/defaults
profile = "library"
change-id = 133068

[build]
optimized-compiler-builtins = true

[target.thumbv7m-vivo-blueos-newlibeabi]
cc = "arm-none-eabi-gcc"
cxx = "arm-none-eabi-g++"
linker = "arm-none-eabi-gcc"
ar = "arm-none-eabi-ar"
ranlib = "arm-none-eabi-ranlib"

[target."thumbv8m.main-vivo-blueos-newlibeabi"]
cc = "arm-none-eabi-gcc"
cxx = "arm-none-eabi-g++"
linker = "arm-none-eabi-gcc"
ar = "arm-none-eabi-ar"
ranlib = "arm-none-eabi-ranlib"

[target."aarch64-vivo-blueos-newlib"]
cc = "aarch64-none-elf-gcc"
cxx = "aarch64-none-elf-g++"
linker = "aarch64-none-elf-gcc"
ar = "aarch64-none-elf-ar"
ranlib = "aarch64-none-elf-ranlib"

[target."riscv64-vivo-blueos"]
cc = "clang"
cxx = "clang++"
linker = "clang"
ar = "llvm-ar"
ranlib = "llvm-ranlib"

[target."riscv32-vivo-blueos"]
cc = "clang"
cxx = "clang++"
linker = "clang"
ar = "llvm-ar"
ranlib = "llvm-ranlib"

[target."riscv32imc-vivo-blueos"]
cc = "clang"
cxx = "clang++"
linker = "clang"
ar = "llvm-ar"
ranlib = "llvm-ranlib"

[target.x86_64-unknown-linux-gnu]
profiler = true

[target.aarch64-apple-darwin]
profiler = true

[rust]
omit-git-hash = false
deny-warnings = false
strip = true

[dist]
compression-formats = ["xz"]

[llvm]
download-ci-llvm = false
