name: Build and test the BlueOS kernel

on:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y ninja generate-ninja qemu-system-arm qemu-system-misc curl

      - name: Install Arm GNU toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: 14.2.Rel1

      - name: Install Arm64 GNU toolchain
        uses: lawkai-vivo/aarch64-none-elf-gcc-action@v1
        with:
          release: 14.2.Rel1

      - name: Download and unpack Rust toolchain
        run: |
          curl -L -o blueos-toolchain.tar.xz https://github.com/lawkai-vivo/test_build_toolchain/releases/download/nightly/blueos-toolchain-2025_08_05_05_43.tar.xz
          mkdir sysroot
          tar xvf blueos-toolchain.tar.xz -C sysroot
          echo "$PWD/sysroot/usr/local/bin" >> "$GITHUB_PATH"

      - name: Init repo and sync
        uses: Xerner/github-actions-android-repo-init-and-sync@0.0.4
        with:
          manifest_url: https://github.com/vivoblueos/manifests.git
          manifest_branch: main
          manifest_filename: manifest.xml

      - name: Run CI script
        run: |
          ./build/ci/run_ci.py
