name: Build and test the BlueOS kernel

on:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build generate-ninja qemu-system-arm qemu-system-misc curl

      - name: Install Arm GNU toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: 14.2.Rel1

      - name: Install Arm64 GNU toolchain
        uses: lawkai-vivo/aarch64-none-elf-gcc-action@v1
        with:
          release: 14.2.Rel1

      - name: Download and unpack Rust toolchain
        run: |
          curl -L -o blueos-toolchain.tar.xz https://github.com/lawkai-vivo/test_build_toolchain/releases/download/nightly/blueos-toolchain-2025_08_05_05_43.tar.xz
          mkdir sysroot
          tar xvf blueos-toolchain.tar.xz -C sysroot
          rm -rvf blueos-toolchain.tar.xz
          echo "$PWD/sysroot/usr/local/bin" >> "$GITHUB_PATH"

      - name: Download Android repo
        run: |
          curl -L -o sysroot/usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          chmod a+x sysroot/usr/local/bin/repo

      - name: Init repo and sync
        run: |
          repo init -u https://github.com/vivoblueos/manifests.git -b main -m manifest.xml
          repo sync -j$(nproc)

      - name: Run CI script
        run: |
          ./build/ci/run_ci.py
