# This is a basic workflow to help you get started with Actions

name: Build and release Rust toolchain for the BlueOS kernel

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout libc
        uses: actions/checkout@v4
        with:
          repository: vivoblueos/libc
          ref: blueos-dev
          path: libc

      - name: Checkout cc-rs
        uses: actions/checkout@v4
        with:
          repository: vivoblueos/cc-rs
          ref: blueos-dev
          path: cc-rs

      - name: Checkout rust
        uses: actions/checkout@v4
        with:
          repository: vivoblueos/rust
          ref: blueos-dev
          path: rust

      - name: Build Rust toolchain
        env:
          DESTDIR: /tmp/blueos-sysroot
          CARGO_NET_GIT_FETCH_WITH_CLI: true
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev pkg-config
          cd rust
          cp config.blueos.toml config.toml
          ./x --help

