name: Test release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make sysroot directory
        run: |
          mkdir -p /tmp/blueos-sysroot/usr/local/{bin,lib}
          touch /tmp/blueos-sysroot/README.md

      - name: Create tarball
        run: |
          tar cJvf toolchain.tar.xz -C /tmp/blueos-sysroot .

      - name: Get release page
        - uses: octokit/request-action@v2.x
          id: get_release_page
          with:
            route: GET /repos/lawkai-vivo/test_build_toolchain/releases/tags/nightly
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release url
        id: get_release_url
        run: |
          url=$(echo "${RESP}" | jq -r '.upload_url')
          echo "url=$url" >> $GITHUB_OUTPUT
        env:
          RESP: ${{ steps.get_release_page.outputs.data }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_url.outputs.url }}
          asset_path: toolchain.tar.xz
          asset_name: toolchain.tar.xz
          asset_content_type: application/x-tar

      - name: Clean up
        run: |
          rm -rf /tmp/blueos-sysroot
